FROM python:3.9-slim

RUN apt-get update && apt-get install -y curl

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs

RUN npm install -g serverless@3 serverless-offline

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

CMD ["serverless", "offline", "--host", "0.0.0.0"]