FROM python:3.9-slim

# Install Node.js 
RUN apt-get update && apt-get install -y nodejs npm

# Install Serverless Framework and the offline plugin globally
RUN npm install -g serverless serverless-offline

# Set the working directory
WORKDIR /app

# Copy python dependencies 
COPY requirements.txt .
RUN pip install -r requirements.txt

# The command to start the local serverless emulator
CMD ["serverless", "offline", "--host", "0.0.0.0"]